# A Guide to NUMPY

In [1]:
import numpy as np

Creating a list and converting it into numpy array.

In [2]:
listt = [2,3,5,9,8,7,9,45]
l = np.array(listt)
l

array([ 2,  3,  5,  9,  8,  7,  9, 45])

In [3]:
t = np.array([2,3,5,9,8,7,9,45])
t

array([ 2,  3,  5,  9,  8,  7,  9, 45])

To create Multi-dimensional Array pass a lists of list.

In [5]:
q = np.array([[2,3,5,9,8,7,9,45],[2,4,5,3,4,6,4,6]])
q

array([[ 2,  3,  5,  9,  8,  7,  9, 45],
       [ 2,  4,  5,  3,  4,  6,  4,  6]])

`arange` is used to return evenly spaced values within a given interval.

In [8]:
p = np.arange(0,50,5)
p

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

`linspace` is used to return evenly spaced numbers over a specified interval.

In [10]:
p = np.linspace(0,3,15)
p

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

`ones` is used to return a new array of given shape and type, filled with ones.

In [11]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`zeros` is used to return a new array of given shape and type, filled with zeros.

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

`eye` is used to return identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`diag` extracts a diagonal or constructs a diagonal array.

In [14]:
q = [1,2,3]
np.diag(q)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

We can create an array using repeating list (or see `np.tile`)

In [3]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

We can repeat elements of an array using `repeat`.

In [5]:
np.repeat([1, 2, 3], 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

#### Combining Arrays

In [6]:
p = np.ones([2, 4], int)

Use `vstack` to stack arrays in sequence horizontally (column wise).

In [7]:
np.vstack([p, 2*p])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [8]:
np.hstack([p, 2*p])

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

## Operations

You can use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [10]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [11]:
print(x+y)

[5 7 9]


In [12]:
print(x-y)

[-3 -3 -3]


In [13]:
print(x*y)

[ 4 10 18]


In [14]:
print(x/y)

[0.25 0.4  0.5 ]


In [15]:
print(x**y)

[  1  32 729]


We can use `.dot()` function to get the dot product.

In [16]:
x.dot(y)

32

We can use `.T` function to transpose the array

In [22]:
z = np.array([x,y])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Numpy has many built in math functions that can be performed on arrays.

In [24]:
x.sum()

6

In [25]:
x.max()

3

In [26]:
x.min()

1

In [27]:
x.mean()

2.0

In [28]:
x.std()

0.816496580927726

`argmax` and `argmin` are used to return the index of the maximum and minimum values in the array.

In [29]:
x.argmax()

2

In [30]:
x.argmin()

0

### Numpy Subsettings

In [11]:
bmi = np.array([24.523,21.265,20.054,26.459,23.245])

In [12]:
bmi>23

array([ True, False, False,  True,  True])

In [13]:
bmi[bmi>23]

array([24.523, 26.459, 23.245])

#### To Find correlation between two rows we use `corrcoef()`

In [14]:
height = np.array([153,160,175,168,175])

In [15]:
np.corrcoef(bmi,height)

array([[ 1.        , -0.27399376],
       [-0.27399376,  1.        ]])